name: Lastest Release

on:
  push:
    branches: [main]

permissions: read-all|write-all

jobs:
  release:
    name: "Lastest Release"
    runs-on: windows-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}\build
    
    - name: Configure CMake
      working-directory: ${{github.workspace}}\build
      run: cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_SHARED_LIBS=OFF -G"Visual Studio 17 2022" -Ax64
    
    - name: Build
      working-directory: ${{github.workspace}}\build
      run: cmake --build . --config MinSizeRel
    
    - name: Zip executable files
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: "zip"
        filename: "IT003.M21.PMCL-Nhom14_v1.0.0.zip"
        path: ${{github.workspace}}\build\MinSizeRel\IT003.M21.PMCL-Nhom14.exe
    
    - name: Public release files
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "v1.x.x"
        prerelease: false
        title: "IT003.M21.PMCL-Nhom14_v1.0.0"
        files: IT003.M21.PMCL-Nhom14_v1.0.0.zip
